import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import ArticlePreview from '../components/article-preview';
import { getRecentArticles } from '../lib/articles';
import styles from '../styles/Home.module.scss';

export default function Home({ length, articles }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Rally Racing Media</title>
                <meta name="description"
                    content="Generated by create next app" />
                <link rel="icon"
                    href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>Rally Racing Media</h1>
                <div className={styles.grid}>
                    {articles.map((a) => {
                        return (
                            <Link href={`${a.link}`}>
                                <a>
                                    <ArticlePreview article={a} />
                                </a>
                            </Link>
                        )
                    })}
                </div>
            </main>
        </div>
    );
}

export const getStaticProps: GetStaticProps = async (context) => {
    const articles = await getRecentArticles();
    console.log('articles', articles);
    return {
        props: {
            length: articles.length,
            articles: articles
        }
    };
};
