import { GetStaticProps } from 'next';
import Head from 'next/head';
import ArticlePreview from '../components/article-preview';
import { getRecentArticles } from '../lib/articles';
import styles from '../styles/Home.module.css';

export default function Home({ length, articles }) {
    return (
        <div className={styles.container}>
      <Head>
        <title>Rally Racing Media</title>
        <meta name="description"
              content="Generated by create next app" />
        <link rel="icon"
              href="/favicon.ico" />
      </Head>

      <main>
        <h1>Home</h1>
          <div className="grid">
              {articles.map((a) => {
                  return <ArticlePreview article={a} />
              })}
          </div>
      </main>
    </div>
    );
}

export const getStaticProps: GetStaticProps = async (context) => {
    const articles = await getRecentArticles();
    console.log('articles', articles);
    return {
        props: {
            length: articles.length,
            articles: articles
        }
    };
};
